// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiWarriorsWebsite.Data;

#nullable disable

namespace WikiWarriorsWebsite.Migrations
{
    [DbContext(typeof(WikiWarriorsWebsiteContext))]
    [Migration("20260219170444_ImprovedFighterHistoryNewRedux")]
    partial class ImprovedFighterHistoryNewRedux
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WikiWarriorsWebsite.Models.FightHistory", b =>
                {
                    b.Property<int>("FightHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FightHistoryId"));

                    b.Property<bool>("DailyFight")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FightDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fighter1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Fighter2Id")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("FightHistoryId");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("FightHistory");
                });

            modelBuilder.Entity("WikiWarriorsWebsite.Models.Fighter", b =>
                {
                    b.Property<int>("FighterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FighterId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LinkCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("FighterId");

                    b.ToTable("Fighter");
                });

            modelBuilder.Entity("WikiWarriorsWebsite.Models.FightHistory", b =>
                {
                    b.HasOne("WikiWarriorsWebsite.Models.Fighter", "Fighter1")
                        .WithMany()
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiWarriorsWebsite.Models.Fighter", "Fighter2")
                        .WithMany()
                        .HasForeignKey("Fighter2Id");

                    b.HasOne("WikiWarriorsWebsite.Models.Fighter", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");

                    b.Navigation("Winner");
                });
#pragma warning restore 612, 618
        }
    }
}
